# Config for drone operator console access
# DroneCorp — internal use only
[internal]
flag_3       = "flag{try_to_connect}"
server_ip    = "192.168.125.55"
ssh_login    = "operator"
ssh_password = "3edcVFR456"
